package com.type;

public enum AmfEventType {
    LOCATION_REPORT,
    PRESENCE_IN_AOI_REPORT,
    TIMEZONE_REPORT,
    ACCESS_TYPE_REPORT,
    REGISTRATION_STATE_REPORT,
    CONNECTIVITY_STATE_REPORT,
    REACHABILITY_REPORT,
    SUBSCRIBED_DATA_REPORT,
    COMMIUNICATION_FAILURE_REPORT,
    UES_IN_AREA_REPORT,
}
