package com.type;

public enum SupportedGADShapes {
    POINT,
    POINT_UNCERTAINTY_CIRCLE,
    POINT_UNCERTAINTY_ELLIPSE,
    POLYGON,
    POINT_ALTITUDE,
    POINT_ALTITUDE_UNCERTAINTY,
    ELLIPSOID_ARC,
}
