package com.type;

public enum Usage {
    UNSUCCESS,
    SUCCESS_RESULTS_NOT_USED,
    SUCCESS_RESULTS_USED_TO_VERIFY_LOCATION,
    SUCCESS_RESULTS_USED_TO_GENERATE_LOCATION,
    SUCCESS_METHOD_NOT_DETERMINED,
}
